# Generated by Django 2.1.7 on 2019-04-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criptomonedasapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='cuerpo',
            field=models.CharField(default='', max_length=256),
        ),
    ]
